// this is for the video game table
const { Game } = require('../models');

const gameData = [
  {
    game_name: 'Grand Theft Auto V',
    developer_id: 1,
    category_id: 1,
    date: '2013-09-17',
  },
  {
    game_name: 'Red Dead Redemption 2',
    developer_id: 1,
    category_id: 1,
    date: '2018-10-26',
  },
  {
    game_name: 'Red Dead Redemption',
    developer_id: 1,
    category_id: 1,
    date: '2010-05-18',
  },
  {
    game_name: 'Grand Theft Auto IV',
    developer_id: 1,
    category_id: 1,
    date: '2008-04-29',
  },
  {
    game_name: 'Grand Theft Auto: San Andreas',
    developer_id: 1,
    category_id: 1,
    date: '2004-10-26',
  },
  {
    game_name: 'Grand Theft Auto: Vice City',
    developer_id: 1,
    category_id: 1,
    date: '2002-10-27',
  },
  {
    game_name: 'Grand Theft Auto III',
    developer_id: 1,
    category_id: 1,
    date: '2001-10-22',
  },
  {
    game_name: 'Grand Theft Auto: London 1969',
    developer_id: 1,
    category_id: 1,
    date: '1999-10-31',
  },
  {
    game_name: 'Grand Theft Auto 2',
    developer_id: 1,
    category_id: 1,
    date: '1999-10-31',
  },
  {
    game_name: 'Grand Theft Auto',
    developer_id: 1,
    category_id: 1,
    date: '1997-10-22',
  },
  {
    game_name: 'The Elder Scrolls V: Skyrim',
    developer_id: 2,
    category_id: 1,
    date: '2011-11-11',
  },
  {
    game_name: 'The Elder Scrolls IV: Oblivion',
    developer_id: 2,
    category_id: 1,
    date: '2006-03-20',
  },
  {
    game_name: 'The Elder Scrolls III: Morrowind',
    developer_id: 2,
    category_id: 1,
    date: '2002-05-01',
  },
  {
    game_name: 'The Elder Scrolls II: Daggerfall',
    developer_id: 2,
    category_id: 1,
    date: '1996-03-02',
  },
  {
    game_name: 'The Elder Scrolls: Arena',
    developer_id: 2,
    category_id: 1,
    date: '1994-11-25',
  },
  {
    game_name: 'The Elder Scrolls: Redguard',
    developer_id: 2,
    category_id: 1,
    date: '1998-11-30',
  },
  {
    game_name: 'The Elder Scrolls: Battlespire',
    developer_id: 2,
    category_id: 1,
    date: '1998-11-30',
  },
  {
    game_name: 'The Elder Scrolls: Morrowind',
    developer_id: 2,
    category_id: 1,
    date: '2002-05-01',
  },
  {
    game_name: 'Super Mario Odyssey',
    developer_id: 2,
    category_id: 1,
    date: '2017-10-27',
  },
  {
    game_name: 'Legend of Zelda: Breath of the Wild',
    developer_id: 2,
    category_id: 1,
    date: '2017-3-3',
  },
  {
    game_name: 'Halo 2',
    developer_id: 2,
    category_id: 1,
    date: '2004-11-9',
    }, 
  {
    game_name: 'Lethal League Blaze',
    developer_id: 2,
    category_id: 1,
    date: '2018-10-24',
  },
  {
    game_name: 'Super Smash Bros. Ultimate',
    developer_id: 2,
    category_id: 1,
    date: '2018-12-07',
  },
  {
    game_name: 'Pokemon Ruby and Sapphire',
    developer_id: 2,
    category_id: 1,
    date: '2002-11-21',
  },
  {
    game_name: 'Castlevania',
    developer_id: 8,
    category_id: 5,
    date: '1987-9-17',
  },
  {
    game_name: 'Castlevania 2 Simons Quest',
    developer_id: 8,
    category_id: 5,
    date: '1989-4-19',
  },
  {
    game_name: 'Castlevania 3',
    developer_id: 8,
    category_id: 5,
    date: '1991-8-16',
  },
  {
    game_name: 'Metroid',
    developer_id: 9,
    category_id: 5,
    date: '1987-7-26',
  },
  {
    game_name: 'Super Mario Bros',
    developer_id: 9,
    category_id: 5,
    date: '1985-5-12',
  },
  {
    game_name: 'Super Mario Bros 2',
    developer_id: 9,
    category_id: 5,
    date: '1987-2-10',
  },
  {
    game_name: 'Super Mario Bros 3',
    developer_id: 9,
    category_id: 5,
    date: '1989-4-7',
  },
  {
    game_name: 'Zelda',
    developer_id: 9,
    category_id: 5,
    date: '1987-3-15',
  },
  {
    game_name: 'Mike Tysons Punch-Out!!',
    developer_id: 9,
    category_id: 5,
    date: '1987-8-9',
  },
  {
    game_name: 'Ninja Gaiden',
    developer_id: 22,
    category_id: 5,
    date: '1989-5-9',
  },
  {
    game_name: 'Ninja Gaiden 2',
    developer_id: 22,
    category_id: 5,
    date: '1991-4-15',
  },
  {
    game_name: 'Ninja Gaiden 3',
    developer_id: 22,
    category_id: 5,
    date: '1992-2-9',
  },
  {
    game_name: 'Tecmo Bowl',
    developer_id: 22,
    category_id: 5,
    date: '1989-3-5',
  },
  {
    game_name: 'Rygar',
    developer_id: 22,
    category_id: 5,
    date: '1986-4-11',
  },
  {
    game_name: 'Contra',
    developer_id: 8,
    category_id: 5,
    date: '1986-5-8',
  },
  {
    game_name: 'LifeForce',
    developer_id: 8,
    category_id: 5,
    date: '1987-4-2',
  },
  {
    game_name: 'MegaMan',
    developer_id: 6,
    category_id: 5,
    date: '1987-4-17',
  },
  {
    game_name: 'MegaMan 2',
    developer_id: 6,
    category_id: 5,
    date: '1988-2-15',
  },
  {
    game_name: 'MegaMan 3',
    developer_id: 6,
    category_id: 5,
    date: '1990-3-12',
  },
  {
    game_name: 'MegaMan 4',
    developer_id: 6,
    category_id: 5,
    date: '1992-8-2',
  },
  {
    game_name: 'MegaMan 5',
    developer_id: 6,
    category_id: 5,
    date: '1993-3-19',
  },
  {
    game_name: 'MegaMan 6',
    developer_id: 6,
    category_id: 5,
    date: '1994-2-14',
  },
  {
    game_name: 'Little Nemo The Dream Master',
    developer_id: 6,
    category_id: 5,
    date: '1990-9-17',
  },
  {
    game_name: 'NHL Hockey 94',
    developer_id: 7,
    category_id: 4,
    date: '1993-3-19',
  },
  {
    game_name: 'NHL Hockey 95',
    developer_id: 7,
    category_id: 4,
    date: '1993-3-19',
  },
  {
    game_name: 'Bayou Billy',
    developer_id: 8,
    category_id: 5,
    date: '1987-4-2',
  },
  {
    game_name: 'Sonic the Hedgehog',
    developer_id: 10,
    category_id: 5,
    date: '1991-6-23',
  },
  {
    game_name: 'Sonic the Hedgehog 2',
    developer_id: 10,
    category_id: 5,
    date: '1993-2-5',
  },
  {
    game_name: 'Sonic the Hedgehog 3',
    developer_id: 10,
    category_id: 5,
    date: '1994-6-22',
  },
  {
    game_name: 'Final Fantasy 7',
    developer_id: 2,
    category_id: 1,
    date: '1997-1-31',
  },
  {
    game_name: 'Crash Bandicoot',
    developer_id: 2,
    category_id: 1,
    date: '1996-11-8',
  },
  {
    game_name: 'Animal Crossing: New Horizons',
    developer_id: 2,
    category_id: 1,
    date: '2020-03-20',
  },
  {
    game_name: 'Uncharted 4',
    developer_id: 2,
    category_id: 1,
    date: '2016-05-10',
  },
  {
    game_name: 'Street Fighter 3:3rd Strike',
    developer_id: 2,
    category_id: 1,
    date: '1999-05-12',
  },
  {
    game_name: 'Splatoon 3',
    developer_id: 2,
    category_id: 1,
    date: '2022-08-27',
  },
  {
    game_name: 'Golden Axe',
    developer_id: 10,
    category_id: 5,
    date: '1989-8-21',
  },
  {
    game_name: 'Golden Axe 2',
    developer_id: 10,
    category_id: 5,
    date: '1991-03-17',
  },
  {
    game_name: 'Streets of Rage',
    developer_id: 10,
    category_id: 5,
    date: '1990-04-6',
  },
  {
    game_name: 'Streets of Rage 2',
    developer_id: 10,
    category_id: 5,
    date: '1991-09-13',
  },
  {
    game_name: 'Streets of Rage 3',
    developer_id: 10,
    category_id: 5,
    date: '1993-05-15',
  },
  {
    game_name: 'John Madden Football 97',
    developer_id: 7,
    category_id: 4,
    date: '1996-3-13',
  },
  {
    game_name: 'John Madden Football 98',
    developer_id: 7,
    category_id: 4,
    date: '1997-02-9',
  },
  {
    game_name: 'Street Fighter 2',
    developer_id: 6,
    category_id: 1,
    date: '1991-02-7',
  },
  {
    game_name: 'Sonic Heroes',
    developer_id: 10,
    category_id: 5,
    date: '2003-12-30',
  },
  {
    game_name: 'Overwatch',
    developer_id: 5,
    category_id: 1,
    date: '2016-05-24',
  },
  {
    game_name: 'Jet Set Radio',
    developer_id: 10,
    category_id: 1,
    date: '2000-06-29',
  },
  {
    game_name: 'Rayman',
    developer_id: 20,
    category_id: 5,
    date: '1995-3-21',
  },
  {
    game_name: 'Rayman 2: The Great Escape',
    developer_id: 20,
    category_id: 5,
    date: '1999-2-4',
  },
  {
    game_name: 'Rayman 3: Hoodlum Havoc',
    developer_id: 20,
    category_id: 5,
    date: '2003-9-3',
  },
  {
    game_name: 'Rayman Origins',
    developer_id: 20,
    category_id: 5,
    date: '2011-5-20',
  },
  {
    game_name: 'Art og Fighting',
    developer_id: 26,
    category_id: 2,
    date: '1992-5-20',
  },
  {
    game_name: 'Art og Fighting 2',
    developer_id: 26,
    category_id: 2,
    date: '1994-5-20',
  },
  {
    game_name: 'King of Fighters 97',
    developer_id: 26,
    category_id: 2,
    date: '1997-2-9',
  },
  

];

const seedGames = () => Game.bulkCreate(gameData);

module.exports = seedGames;
